import iphone15pro from './gorsel/iPhone15Pro.webp'
import samsungGalaxyS24 from './gorsel/SamsungGalaxyS24.webp'
import xiaomiRedmiNote13 from './gorsel/XiaomiRedmiNote13.webp'
import macbookAirM3 from './gorsel/MacBookAirM3.webp'
import thinkpadE14 from './gorsel/ThinkPadE14.webp'
import asusRogStrix from './gorsel/ASUSROGStrixG16.webp'
import airpodsPro2 from './gorsel/AirPodsPro2.webp'
import logitechMxMaster from './gorsel/LogitechMXMaster3S.webp'

export const products = [
  {
    id: 1,
    name: 'iPhone 15 Pro',
    category: 'Telefon',
    price: 54999,
    oldPrice: 59999,
    image: iphone15pro,
    description: 'iPhone 15 Pro, A17 Pro çip ve titanyum tasarımıyla Apple\'ın en güçlü iPhone\'u. Gelişmiş kamera sistemi, USB 3 hızları ve yeni Aksiyon Düğmesi ile profesyonel düzeyde fotoğraf ve video deneyimi sunar.',
    specs: [
      'A17 Pro çip (3nm teknoloji)',
      '6.1 inç Super Retina XDR ekran',
      '48MP Ana + 12MP Ultra Geniş + 12MP Telefoto',
      '256GB depolama',
      'USB 3 (40Gb/s)',
      'Titanyum gövde',
      'iOS 17',
    ],
  },
  {
    id: 2,
    name: 'Samsung Galaxy S24',
    category: 'Telefon',
    price: 44999,
    oldPrice: null,
    image: samsungGalaxyS24,
    description: 'Galaxy S24, Snapdragon 8 Gen 3 işlemci ve Galaxy AI özellikleriyle akıllı telefon deneyimini yeniden tanımlıyor. 50MP kamera, 7 yıl yazılım güncellemesi ve ince tasarımıyla öne çıkıyor.',
    specs: [
      'Snapdragon 8 Gen 3 işlemci',
      '6.2 inç Dynamic AMOLED 2X ekran',
      '50MP Ana + 12MP Ultra Geniş + 10MP Telefoto',
      '256GB depolama',
      '4000mAh pil',
      '25W hızlı şarj',
      'Android 14, Galaxy AI',
    ],
  },
  {
    id: 3,
    name: 'Xiaomi Redmi Note 13',
    category: 'Telefon',
    price: 14999,
    oldPrice: 17999,
    image: xiaomiRedmiNote13,
    description: 'Redmi Note 13, 200MP kamera ve AMOLED ekranıyla bütçe dostu segmentin en iddialı modeli. Güçlü pil ömrü ve hızlı şarj teknolojisiyle günlük kullanımda mükemmel performans sunar.',
    specs: [
      'Snapdragon 685 işlemci',
      '6.67 inç AMOLED FHD+ ekran',
      '200MP Ana + 8MP Ultra Geniş + 2MP Makro',
      '128GB depolama',
      '5000mAh pil',
      '33W hızlı şarj',
      'Android 13, MIUI 14',
    ],
  },
  {
    id: 4,
    name: 'MacBook Air M3',
    category: 'Laptop',
    price: 54999,
    oldPrice: null,
    image: macbookAirM3,
    description: 'MacBook Air M3, Apple\'ın en ince ve hafif laptopu. Tüm gün süren pil ömrü, sessiz fanless tasarım ve güçlü M3 çipiyle yaratıcı profesyoneller ve öğrenciler için ideal seçim.',
    specs: [
      'Apple M3 çip (8 çekirdekli CPU)',
      '13.6 inç Liquid Retina ekran',
      '8GB birleşik bellek',
      '256GB SSD',
      '18 saate kadar pil ömrü',
      'MagSafe 3 şarj',
      'macOS Sonoma',
    ],
  },
  {
    id: 5,
    name: 'Lenovo ThinkPad E14',
    category: 'Laptop',
    price: 28999,
    oldPrice: 32999,
    image: thinkpadE14,
    description: 'ThinkPad E14, dayanıklı yapısı ve iş odaklı özellikleriyle kurumsal kullanıcıların tercihi. Intel Core i5 işlemci, hızlı SSD ve uzun pil ömrüyle ofis ve uzaktan çalışma için optimize edilmiştir.',
    specs: [
      'Intel Core i5-1335U işlemci',
      '14 inç FHD IPS ekran',
      '16GB DDR4 RAM',
      '512GB SSD',
      'Intel Iris Xe grafik',
      '57Whr pil',
      'Windows 11 Pro',
    ],
  },
  {
    id: 6,
    name: 'ASUS ROG Strix G16',
    category: 'Laptop',
    price: 47999,
    oldPrice: null,
    image: asusRogStrix,
    description: 'ROG Strix G16, RTX 4070 ekran kartı ve 240Hz ekranıyla rekabetçi oyunculara yönelik tasarlanmış üst segment gaming laptop. Gelişmiş soğutma sistemi ve RGB aydınlatmasıyla tam anlamıyla bir oyun canavarı.',
    specs: [
      'Intel Core i9-13980HX işlemci',
      '16 inç QHD+ 240Hz ekran',
      'NVIDIA RTX 4070 8GB',
      '32GB DDR5 RAM',
      '1TB NVMe SSD',
      'ROG Intelligent Cooling',
      'Windows 11 Home',
    ],
  },
  {
    id: 7,
    name: 'AirPods Pro 2',
    category: 'Aksesuar',
    price: 8999,
    oldPrice: 10999,
    image: airpodsPro2,
    description: 'AirPods Pro 2. nesil, endüstri lideri Aktif Gürültü Engelleme ve Uyarlanabilir Ses teknolojisiyle müzik deneyimini üst seviyeye taşıyor. MagSafe şarj kutusu ve kişiselleştirilmiş Uzamsal Ses desteği sunar.',
    specs: [
      'H2 çip',
      'Aktif Gürültü Engelleme',
      'Uyarlanabilir Şeffaflık Modu',
      'Kişiselleştirilmiş Uzamsal Ses',
      '6 saate kadar dinleme süresi',
      'MagSafe şarj kutusu',
      'IPX4 su dayanıklılığı',
    ],
  },
  {
    id: 8,
    name: 'Logitech MX Master 3S',
    category: 'Aksesuar',
    price: 3499,
    oldPrice: null,
    image: logitechMxMaster,
    description: 'MX Master 3S, 8000 DPI hassasiyeti ve sessiz tıklama teknolojisiyle profesyoneller için tasarlanmış en gelişmiş ergonomik mouse. Çoklu cihaz desteği ve hızlı şarj özelliğiyle verimliliği maksimuma taşır.',
    specs: [
      '8000 DPI hassasiyet',
      'Sessiz tıklama teknolojisi',
      'MagSpeed elektromanyetik kaydırma',
      '3 cihaza kadar Bluetooth bağlantısı',
      '70 günlük pil ömrü',
      '1 dakika şarj = 3 saat kullanım',
      'Windows & macOS uyumlu',
    ],
  },
]